### ISSUE TITLE
Buffers overflow on socket_send

### ISSUE THREAD

**Issue by foxik0169** [rytc/enet-jai#4]
Hey, I think I found another bug,

when I use the library on windows It tries to iterate over host.buffers with host.buffer_count which results in failed assertion, because host.buffer_count can be bigger than size of the buffers array which is currently set to MSG_MAXIOVLEN on Windows. This doesn't happen when I have short timeout for host_service() (1ms). If I change MAX_BUFFER_COUNT to the same value as other OSes (1+2*PROTOCOL_MAX_PACKET_COMMANDS), then it works even with large timeouts (30 seconds). Seems to me like there is some code that relies on host.buffers being bigger than they actually are? 

Hopefully this could will help with solving this issue.

Daniel

**Comment by rytc** [comment]
Hi, I wasn't able to reproduce it but I suspect I know where the error happened. I pushed up a fix for it, let me know if it works. If not, let me know some more details like client count, packet size, packet type, etc.

**Comment by foxik0169** [comment]
I will try to create reproduction code and send it to you. However I find it difficult to do it disconnected from the game I am working on. Maybe this can happen only when threads are involved. Not sure myself. The fix in the repo did not help.

**Comment by foxik0169** [comment]
I've created a gist here: https://gist.github.com/foxik0169/519988ace73309e3ba9349644159fa42

The thing is, that it happens only with unreliable packets and when there is enough data.... Expected output:
```
Running as SERVER
Server started...
A client has connected!
Array bounds check failed. (The attempted index is 16, but the highest valid index is 15). Site is C:/Users/foxik0169/Projects/enet-jai/modules/enet/examples/../../enet/socket.jai:156.
Panic.
A breakpoint was hit, but no debugger is attached.

Printing the stack trace:
handle_exception                  C:\Users\foxik0169\Toolkits\jai-current\modules\Runtime_Support_Crash_Handler.jai:361
... (skipping OS-internal procedures)
my_panic                          C:\Users\foxik0169\Toolkits\jai-current\modules\Runtime_Support.jai:354
__array_bounds_check_fail         C:\Users\foxik0169\Toolkits\jai-current\modules\Runtime_Support.jai:160
socket_send                       C:\Users\foxik0169\Projects\enet-jai\modules\enet\socket.jai:156
protocol_send_outgoing_commands   C:\Users\foxik0169\Projects\enet-jai\modules\enet\protocol.jai:302
host_service                      C:\Users\foxik0169\Projects\enet-jai\modules\enet\host.jai:215
run_server                        C:\Users\foxik0169\Projects\enet-jai\modules\enet\examples\reproduction_4.jai:44
main                              C:\Users\foxik0169\Projects\enet-jai\modules\enet\examples\reproduction_4.jai:19
```

**Comment by rytc** [comment]
Thanks for the repro example, I submitted a fix in the latest commit

**Comment by rytc** [comment]
Confirmed fixed on discord.
